name: MMOItemsEquipExpansion
version: '1.0-SNAPSHOT'
main: com.gmail.bobason01.mmoitemsequipexpansion.MMOItemsEquipExpansion
api-version: '1.21'
authors: [crston]
description: You can check the stats of each MMOItems Equipment with PAPI
depend: [MMOItems, PlaceholderAPI]